"""add status column in task table

Revision ID: 63451425095c
Revises: 66f087658a61
Create Date: 2024-02-26 19:17:39.824332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63451425095c'
down_revision = '66f087658a61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
